//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_of_Battleships.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("World_of_Battleships.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BBackToMenuPassive {
            get {
                object obj = ResourceManager.GetObject("BBackToMenuPassive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BControlsPassive {
            get {
                object obj = ResourceManager.GetObject("BControlsPassive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BStartActive {
            get {
                object obj = ResourceManager.GetObject("BStartActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BStartPassive {
            get {
                object obj = ResourceManager.GetObject("BStartPassive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Controls {
            get {
                object obj = ResourceManager.GetObject("Controls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Defeat {
            get {
                return ResourceManager.GetStream("Defeat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DefeatedInfo {
            get {
                object obj = ResourceManager.GetObject("DefeatedInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Destroy1 {
            get {
                return ResourceManager.GetStream("Destroy1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Destroy2 {
            get {
                return ResourceManager.GetStream("Destroy2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Destroy3 {
            get {
                return ResourceManager.GetStream("Destroy3", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DestroyInfo {
            get {
                object obj = ResourceManager.GetObject("DestroyInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EmptyWater {
            get {
                object obj = ResourceManager.GetObject("EmptyWater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Error {
            get {
                return ResourceManager.GetStream("Error", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Hit {
            get {
                object obj = ResourceManager.GetObject("Hit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HitInfo {
            get {
                object obj = ResourceManager.GetObject("HitInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Hitted1 {
            get {
                return ResourceManager.GetStream("Hitted1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Hitted2 {
            get {
                return ResourceManager.GetStream("Hitted2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Hitted3 {
            get {
                return ResourceManager.GetStream("Hitted3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Hitted4 {
            get {
                return ResourceManager.GetStream("Hitted4", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap InvalidShipPlaceInfo {
            get {
                object obj = ResourceManager.GetObject("InvalidShipPlaceInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InvalidTargetInfo {
            get {
                object obj = ResourceManager.GetObject("InvalidTargetInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Miss {
            get {
                object obj = ResourceManager.GetObject("Miss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Missed1 {
            get {
                return ResourceManager.GetStream("Missed1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Missed2 {
            get {
                return ResourceManager.GetStream("Missed2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MissInfo {
            get {
                object obj = ResourceManager.GetObject("MissInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PlaceShip {
            get {
                return ResourceManager.GetStream("PlaceShip", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Sea {
            get {
                return ResourceManager.GetStream("Sea", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Ship {
            get {
                object obj = ResourceManager.GetObject("Ship", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream StartBattle {
            get {
                return ResourceManager.GetStream("StartBattle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Target {
            get {
                object obj = ResourceManager.GetObject("Target", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Victory {
            get {
                return ResourceManager.GetStream("Victory", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap VictoryInfo {
            get {
                object obj = ResourceManager.GetObject("VictoryInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
